import type { ModelProfile } from "./types";

const SEED_NOTE = "Seed estimate (2026-07) — verify and override with your real pricing and measured latency.";

/**
 * Seed registry (updated 2026-07-12). Anthropic figures match the official
 * docs; OpenAI (GPT-5.6 family) and Google (Gemini 3.x) pricing match each
 * vendor's published API pricing as of July 2026. Capability/latency values
 * are editable seeds: good enough to route sensibly on day one, meant to be
 * overridden per user config and corrected by Apollo's own telemetry
 * (`apollo stats` / `apollo calibrate`).
 */
export const DEFAULT_MODELS: ModelProfile[] = [
  {
    id: "anthropic/claude-fable-5",
    provider: "anthropic",
    displayName: "Claude Fable 5",
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    capabilities: { code: 0.97, reasoning: 0.99, writing: 0.95, vision: 0.9, "tool-use": 0.97, "long-context": 0.95 },
    cost: { inputPerMTok: 10, outputPerMTok: 50 },
    latency: { ttftMs: 1200, tokensPerSec: 40 },
    notes: "Frontier tier. Pricing/context per Anthropic docs 2026-07.",
  },
  {
    id: "anthropic/claude-opus-4-8",
    provider: "anthropic",
    displayName: "Claude Opus 4.8",
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    capabilities: { code: 0.96, reasoning: 0.95, writing: 0.93, vision: 0.92, "tool-use": 0.95, "long-context": 0.92 },
    cost: { inputPerMTok: 5, outputPerMTok: 25 },
    latency: { ttftMs: 900, tokensPerSec: 55 },
    notes: "Pricing/context per Anthropic docs 2026-07.",
  },
  {
    id: "anthropic/claude-sonnet-4-6",
    provider: "anthropic",
    displayName: "Claude Sonnet 4.6",
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    capabilities: { code: 0.88, reasoning: 0.86, writing: 0.86, vision: 0.85, "tool-use": 0.9, "long-context": 0.85 },
    cost: { inputPerMTok: 3, outputPerMTok: 15 },
    latency: { ttftMs: 600, tokensPerSec: 75 },
    notes: "Pricing/context per Anthropic docs 2026-07.",
  },
  {
    id: "anthropic/claude-haiku-4-5",
    provider: "anthropic",
    displayName: "Claude Haiku 4.5",
    contextWindow: 200_000,
    maxOutputTokens: 64_000,
    capabilities: { code: 0.72, reasoning: 0.68, writing: 0.7, vision: 0.7, "tool-use": 0.78, "long-context": 0.55 },
    cost: { inputPerMTok: 1, outputPerMTok: 5 },
    latency: { ttftMs: 350, tokensPerSec: 110 },
    notes: "Pricing/context per Anthropic docs 2026-07.",
  },
  {
    id: "openai/gpt-5.6-sol",
    provider: "openai",
    displayName: "GPT-5.6 Sol",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    capabilities: { code: 0.94, reasoning: 0.95, writing: 0.9, vision: 0.88, "tool-use": 0.93, "long-context": 0.85 },
    cost: { inputPerMTok: 5, outputPerMTok: 30 },
    latency: { ttftMs: 800, tokensPerSec: 60 },
    notes: `OpenAI flagship (GPT-5.6 family, GA 2026-07). Pricing per OpenAI docs 2026-07; ${SEED_NOTE}`,
  },
  {
    id: "openai/gpt-5.6-terra",
    provider: "openai",
    displayName: "GPT-5.6 Terra",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    capabilities: { code: 0.89, reasoning: 0.89, writing: 0.86, vision: 0.83, "tool-use": 0.89, "long-context": 0.82 },
    cost: { inputPerMTok: 2.5, outputPerMTok: 15 },
    latency: { ttftMs: 500, tokensPerSec: 90 },
    notes: `Mid tier of the GPT-5.6 family. Pricing per OpenAI docs 2026-07; ${SEED_NOTE}`,
  },
  {
    id: "openai/gpt-5.6-luna",
    provider: "openai",
    displayName: "GPT-5.6 Luna",
    contextWindow: 400_000,
    maxOutputTokens: 64_000,
    capabilities: { code: 0.76, reasoning: 0.74, writing: 0.74, vision: 0.72, "tool-use": 0.8, "long-context": 0.7 },
    cost: { inputPerMTok: 1, outputPerMTok: 6 },
    latency: { ttftMs: 300, tokensPerSec: 140 },
    notes: `Fast/cheap tier of the GPT-5.6 family. Pricing per OpenAI docs 2026-07; ${SEED_NOTE}`,
  },
  {
    id: "google/gemini-3.1-pro",
    nativeId: "gemini-3.1-pro-preview",
    provider: "google",
    displayName: "Gemini 3.1 Pro (preview)",
    contextWindow: 1_000_000,
    maxOutputTokens: 65_000,
    capabilities: { code: 0.88, reasoning: 0.93, writing: 0.86, vision: 0.94, "tool-use": 0.89, "long-context": 0.97 },
    cost: { inputPerMTok: 2, outputPerMTok: 12 },
    latency: { ttftMs: 700, tokensPerSec: 70 },
    notes: `Pricing per Google AI docs 2026-07 (≤200K-token prompts; higher above); ${SEED_NOTE}`,
  },
  {
    id: "google/gemini-3.5-flash",
    provider: "google",
    displayName: "Gemini 3.5 Flash",
    contextWindow: 1_000_000,
    maxOutputTokens: 65_000,
    capabilities: { code: 0.82, reasoning: 0.82, writing: 0.78, vision: 0.86, "tool-use": 0.82, "long-context": 0.9 },
    cost: { inputPerMTok: 1.5, outputPerMTok: 9 },
    latency: { ttftMs: 350, tokensPerSec: 130 },
    notes: `Pricing per Google AI docs 2026-07; ${SEED_NOTE}`,
  },
  {
    id: "google/gemini-3.1-flash-lite",
    provider: "google",
    displayName: "Gemini 3.1 Flash-Lite",
    contextWindow: 1_000_000,
    maxOutputTokens: 65_000,
    capabilities: { code: 0.62, reasoning: 0.6, writing: 0.62, vision: 0.7, "tool-use": 0.65, "long-context": 0.8 },
    cost: { inputPerMTok: 0.25, outputPerMTok: 1.5 },
    latency: { ttftMs: 250, tokensPerSec: 180 },
    notes: `Cheapest Google tier. Pricing per Google AI docs 2026-07; ${SEED_NOTE}`,
  },
  {
    id: "codex/gpt-5.6-terra",
    nativeId: "gpt-5.6-terra",
    provider: "codex",
    displayName: "GPT-5.6 Terra (ChatGPT subscription)",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    capabilities: { code: 0.9, reasoning: 0.89, writing: 0.84, "tool-use": 0.9, "long-context": 0.82 },
    cost: { inputPerMTok: 0, outputPerMTok: 0 },
    latency: { ttftMs: 700, tokensPerSec: 85 },
    notes:
      "ChatGPT subscription default via `codex login` — no marginal cost, plan-quota limited. Older codex models (gpt-5.3-codex and earlier) retire 2026-07-23.",
  },
  {
    id: "codex/gpt-5.6-sol",
    nativeId: "gpt-5.6-sol",
    provider: "codex",
    displayName: "GPT-5.6 Sol (ChatGPT subscription)",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    capabilities: { code: 0.94, reasoning: 0.94, writing: 0.88, "tool-use": 0.93, "long-context": 0.85 },
    cost: { inputPerMTok: 0, outputPerMTok: 0 },
    latency: { ttftMs: 900, tokensPerSec: 55 },
    notes: "ChatGPT subscription 'Power' tier via `codex login` — no marginal cost, plan-quota limited.",
  },
  {
    id: "gemini-cli/gemini-3-flash",
    nativeId: "gemini-3-flash",
    provider: "gemini-cli",
    displayName: "Gemini 3 Flash (Google login)",
    contextWindow: 1_000_000,
    maxOutputTokens: 65_000,
    capabilities: { code: 0.78, reasoning: 0.8, writing: 0.76, vision: 0.85, "tool-use": 0.8, "long-context": 0.9 },
    cost: { inputPerMTok: 0, outputPerMTok: 0 },
    latency: { ttftMs: 700, tokensPerSec: 100 },
    notes:
      "Google account via Gemini CLI login — free-tier quota. NOTE: Gemini CLI was discontinued 2026-06-18 (successor: Antigravity CLI); works only with a pre-existing login, and Pro models went paid 2026-03.",
  },
  {
    id: "ollama/qwen3-coder-30b",
    nativeId: "qwen3-coder:30b",
    provider: "ollama",
    displayName: "Qwen3 Coder 30B (local)",
    contextWindow: 262_144,
    maxOutputTokens: 32_000,
    capabilities: { code: 0.66, reasoning: 0.5, writing: 0.45, "tool-use": 0.6, "long-context": 0.4 },
    cost: { inputPerMTok: 0, outputPerMTok: 0 },
    latency: { ttftMs: 250, tokensPerSec: 45 },
    notes: "Local via Ollama — free and private; throughput depends on hardware.",
  },
];
