/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMissionsRouteImport } from './routes/_authenticated/missions'
import { Route as AuthenticatedMemoriesRouteImport } from './routes/_authenticated/memories'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as ApiVoiceTranscriptRouteImport } from './routes/api/voice/transcript'
import { Route as ApiVoiceTokenRouteImport } from './routes/api/voice/token'
import { Route as ApiVoiceRecallRouteImport } from './routes/api/voice/recall'
import { Route as ApiMissionsStreamRouteImport } from './routes/api/missions/stream'
import { Route as AuthenticatedMissionsIdRouteImport } from './routes/_authenticated/missions.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMissionsRoute = AuthenticatedMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMemoriesRoute = AuthenticatedMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiVoiceTranscriptRoute = ApiVoiceTranscriptRouteImport.update({
  id: '/api/voice/transcript',
  path: '/api/voice/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTokenRoute = ApiVoiceTokenRouteImport.update({
  id: '/api/voice/token',
  path: '/api/voice/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRecallRoute = ApiVoiceRecallRouteImport.update({
  id: '/api/voice/recall',
  path: '/api/voice/recall',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMissionsStreamRoute = ApiMissionsStreamRouteImport.update({
  id: '/api/missions/stream',
  path: '/api/missions/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMissionsIdRoute = AuthenticatedMissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/memories': typeof AuthenticatedMemoriesRoute
  '/missions': typeof AuthenticatedMissionsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/missions/$id': typeof AuthenticatedMissionsIdRoute
  '/api/missions/stream': typeof ApiMissionsStreamRoute
  '/api/voice/recall': typeof ApiVoiceRecallRoute
  '/api/voice/token': typeof ApiVoiceTokenRoute
  '/api/voice/transcript': typeof ApiVoiceTranscriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/memories': typeof AuthenticatedMemoriesRoute
  '/missions': typeof AuthenticatedMissionsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/missions/$id': typeof AuthenticatedMissionsIdRoute
  '/api/missions/stream': typeof ApiMissionsStreamRoute
  '/api/voice/recall': typeof ApiVoiceRecallRoute
  '/api/voice/token': typeof ApiVoiceTokenRoute
  '/api/voice/transcript': typeof ApiVoiceTranscriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/_authenticated/memories': typeof AuthenticatedMemoriesRoute
  '/_authenticated/missions': typeof AuthenticatedMissionsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/missions/$id': typeof AuthenticatedMissionsIdRoute
  '/api/missions/stream': typeof ApiMissionsStreamRoute
  '/api/voice/recall': typeof ApiVoiceRecallRoute
  '/api/voice/token': typeof ApiVoiceTokenRoute
  '/api/voice/transcript': typeof ApiVoiceTranscriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/agents'
    | '/chat'
    | '/keys'
    | '/memories'
    | '/missions'
    | '/settings'
    | '/voice'
    | '/api/chat'
    | '/missions/$id'
    | '/api/missions/stream'
    | '/api/voice/recall'
    | '/api/voice/token'
    | '/api/voice/transcript'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/agents'
    | '/chat'
    | '/keys'
    | '/memories'
    | '/missions'
    | '/settings'
    | '/voice'
    | '/api/chat'
    | '/missions/$id'
    | '/api/missions/stream'
    | '/api/voice/recall'
    | '/api/voice/token'
    | '/api/voice/transcript'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authenticated/agents'
    | '/_authenticated/chat'
    | '/_authenticated/keys'
    | '/_authenticated/memories'
    | '/_authenticated/missions'
    | '/_authenticated/settings'
    | '/_authenticated/voice'
    | '/api/chat'
    | '/_authenticated/missions/$id'
    | '/api/missions/stream'
    | '/api/voice/recall'
    | '/api/voice/token'
    | '/api/voice/transcript'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiMissionsStreamRoute: typeof ApiMissionsStreamRoute
  ApiVoiceRecallRoute: typeof ApiVoiceRecallRoute
  ApiVoiceTokenRoute: typeof ApiVoiceTokenRoute
  ApiVoiceTranscriptRoute: typeof ApiVoiceTranscriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions': {
      id: '/_authenticated/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedMissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/memories': {
      id: '/_authenticated/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AuthenticatedMemoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/voice/transcript': {
      id: '/api/voice/transcript'
      path: '/api/voice/transcript'
      fullPath: '/api/voice/transcript'
      preLoaderRoute: typeof ApiVoiceTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/token': {
      id: '/api/voice/token'
      path: '/api/voice/token'
      fullPath: '/api/voice/token'
      preLoaderRoute: typeof ApiVoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/recall': {
      id: '/api/voice/recall'
      path: '/api/voice/recall'
      fullPath: '/api/voice/recall'
      preLoaderRoute: typeof ApiVoiceRecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/missions/stream': {
      id: '/api/missions/stream'
      path: '/api/missions/stream'
      fullPath: '/api/missions/stream'
      preLoaderRoute: typeof ApiMissionsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/missions/$id': {
      id: '/_authenticated/missions/$id'
      path: '/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof AuthenticatedMissionsIdRouteImport
      parentRoute: typeof AuthenticatedMissionsRoute
    }
  }
}

interface AuthenticatedMissionsRouteChildren {
  AuthenticatedMissionsIdRoute: typeof AuthenticatedMissionsIdRoute
}

const AuthenticatedMissionsRouteChildren: AuthenticatedMissionsRouteChildren = {
  AuthenticatedMissionsIdRoute: AuthenticatedMissionsIdRoute,
}

const AuthenticatedMissionsRouteWithChildren =
  AuthenticatedMissionsRoute._addFileChildren(
    AuthenticatedMissionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedMemoriesRoute: typeof AuthenticatedMemoriesRoute
  AuthenticatedMissionsRoute: typeof AuthenticatedMissionsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedMemoriesRoute: AuthenticatedMemoriesRoute,
  AuthenticatedMissionsRoute: AuthenticatedMissionsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiMissionsStreamRoute: ApiMissionsStreamRoute,
  ApiVoiceRecallRoute: ApiVoiceRecallRoute,
  ApiVoiceTokenRoute: ApiVoiceTokenRoute,
  ApiVoiceTranscriptRoute: ApiVoiceTranscriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
